/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio3p1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.beans.Transient;

class AppTest {
    @Test 
    public void testVacio(){
        App app = new App();
        String palabra = "";
        
        assertEquals(0,app.Add(palabra));
    }

    @Test
    public void masDeTres(){
        App app = new App();
        String palabra = "5,2,8";

        assertThrows(IllegalArgumentException.class, () -> {
            app.Add(palabra);
        });
    }

    @Test
    public void suma1(){
        App app = new App();

        String palabra = "5";
        int resul = app.Add(palabra);
        assertEquals(5,resul);
    }

    @Test
    public void suma2(){
        App app = new App();

        String palabra = "5,2";
        int resul = app.Add(palabra);
        assertEquals(7,resul);
    }

    @Test
    public void saltoLinea(){
        App app = new App();

        String palabra = "1\n2";
        int resul = app.Add(palabra);
        assertEquals(3,resul);
    }
}
