/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio3p1;

import java.util.ArrayList;

public class App { 
    public static void main(String[] args) {
        //
    }

    public App(){

    }

    public int Add(String palabra){
        if(palabra.isEmpty()){
            return 0;
        }
        String[] arrNumeros = palabra.split(",");
        ArrayList<String> listaFinal = new ArrayList();

        //Lista final contendrá todos los arreglos spliteados por coma y endline
        for(String string : arrNumeros){
            String salto = "\n";
            if(string.contains(salto)){
                String[] arrAux = string.split(salto);
                for(String stringAux: arrAux){
                    listaFinal.add(stringAux);
                }
            }else{
                listaFinal.add(string);
            }
        }
        
        int sum = 0;
        String numStr;
        for(String string : listaFinal){
            numStr = string;
            sum += Integer.parseInt(numStr);
        }
  
        return sum;
    }
}
